import re
for line in open("output.txt"):
 if "{" in line:
     energy = line.split()
     energy[1] = re.sub("[,]", "", energy[1])
     file_name = [energy[1][-4:], ".cif"]
     file_name2 = ''.join(file_name)
     f = open(file_name2, 'w')
 if "abc" in line:
     f.write("data_TiS2\n")
     f.write("_symmetry_space_group_name_H-M          'P 1'\n")
     temp1 = line.split()
     cell_parameters = [temp1[2], temp1[3], temp1[4]]
     a = ["_cell_length_a ", cell_parameters[0], "\n"]
     b = ["_cell_length_b ", cell_parameters[1], "\n"]
     c = ["_cell_length_c ", cell_parameters[2], "\n"]
     f.writelines (a)
     f.writelines (b)
     f.writelines (c)
 if "angles" in line:
     temp2 = line.split()
     cell_angles = [temp2[2], temp2[3], temp2[4]]
     alpha = ["_cell_angle_alpha ", cell_angles[0], "\n"]
     beta = ["_cell_angle_beta ", cell_angles[1], "\n"]
     gamma = ["_cell_angle_gamma ", cell_angles[2], "\n"]
     f.writelines (alpha)
     f.writelines (beta)
     f.writelines (gamma)
     y = '''_chemical_name_systematic               'Generated by pymatgen'
_symmetry_Int_Tables_number             1
_chemical_formula_structural            Li2MnSiO4
_chemical_formula_sum                   'Li4 Mn2 Si2 O8'
_cell_volume                            175.842145987
_cell_formula_units_Z                   2

loop_
  _symmetry_equiv_pos_site_id
  _symmetry_equiv_pos_as_xyz
   1  'x, y, z'
 
loop_
  _atom_site_type_symbol
  _atom_site_fract_x
  _atom_site_fract_y
  _atom_site_fract_z\n'''
     f.write (y)
 if "PeriodicSite" in line:
     temp3 = line.split()
     site = [temp3[1], temp3[5], temp3[6], temp3[7]]
     site[0] = re.sub("\d", "", site[0])
     site[0] = re.sub("[+]", "", site[0])
     site[0] = re.sub("[-]", "", site[0])
     site[0] = re.sub("Zr", "Ti", site[0]) #remove if not needed - replacement of Zr with Ti
     site[1] = re.sub("[,]", "", site[1])
     site[2] = re.sub("[,]", "", site[2])
     site[3] = re.sub("[,]", "", site[3])
     site[1] = re.sub("[[]", "", site[1])
     site[2] = re.sub("[[]", "", site[2])
     site[3] = re.sub("[[]", "", site[3])
     site[1] = re.sub("[]]", "", site[1])
     site[2] = re.sub("[]]", "", site[2])
     site[3] = re.sub("[]]", "", site[3])
     site[1] = re.sub("[}]", "", site[1])
     site[2] = re.sub("[}]", "", site[2])
     site[3] = re.sub("[}]", "", site[3])
     site2 = [site[0], " ", site[1], " ", site[2], " ", site[3], "\n"]
     f.writelines (site2)
 if "}" in line:
     f.close()




